language: python
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python-lxml python-pip
install:
- deactivate
- gem install kramdown-rfc2629
- sudo pip install xml2rfc
script: make ghpages
env:
  global:
    secure: B4Ypm/dG4ZyGTy91LzK5zVcRU+M3Lz8nfo7WcjuYBIRzrtv36bGHsMz/GiAI0d6yF7kQpageDATsOravKzCk8OTRVJ8HrW/0GqEGis2NleKkA7WgODRjNYENUrZfOHLLjBywB4f1qcE0YNjkBIBAUoYLRi/oNANCoZXL8MtJpTelvHm3QofHhOxZLAwYf4lcYmsswAlYOWKRUZr5YIKDcH96b1jHgOGKNc9oC/2Pj0P0r7tCSrm8Nl5wsqaJEELu18ZEUI0MN4gX16J9SnJCdZRTj5w0Sfx5qv2Q+IBALWDK3jrPoAUIzIb7L3UbUIgBuaIvzH8/T3I9l4dG2YjvchrzIh4lb9OM6hlDJhWviqBYqhgLx/9Vfoy7UuOLbzls4R4P3OHpCmSmMddTMbpSgZO/EjjAop1PS6AwpJrJiMZWSjjK/6kex/mp0y3uWUvpngvBJ+MlU4QZpt11tOzK7bwoWH4M3G4rqf80SWQGipdhwB3AdyR7u9vtGSiHNWiHgxpneB5jcKTlNyL15eM/A6YgDPVjruyuRbZJZvLkT9lNWaIkPmb5G1LNzy28L4YIDOD/giYoaChH59w6M22pnnCLCc47hd3KAyBN908tKp5nj/W+0fJZRJHkHKN7uBOH+yo1ds1jLtPqbuHEmBrHyTJt3Otb0sMSddIhmiL2q/s=
